---
name: build nodejs application
on: 
  workflow_dispatch:
    branch:
      - master
    pull_request:
      - master
jobs:
  job1:
    runs-on: ubuntu_latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v6
      with:
        ref: 'master'  # Optional
    - name: Install Node Js
      uses: actions/setup-node@v6
      with:
        node-version: 18
        cache: npm
    - name: Install node dependensies
      run: npm ci       # aliase npm clean install
    - name: Execute test cases
      run: npm test
    - name: Build the node js code
      run: npm run build